plugins {
    id 'java'
}

group = 'com.korebit'
version = '0.2.7'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.korebit.Main'
        )
    }
}